<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RentalFlow.Application\RentalFlow.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Extensions.Microsoft.DependencyInjection" Version="6.0.2" />
    <PackageReference Include="LiteBus.Extensions.Microsoft.DependencyInjection" Version="6.0.2" />
    <PackageReference Include="LiteBus.Messaging.Extensions.Microsoft.DependencyInjection" Version="6.0.2" />
    <PackageReference Include="LiteBus.Queries.Extensions.Microsoft.DependencyInjection" Version="6.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
